application_name               = "DevOps1-pm1"
environment                    = "dev"
location                       = "South africa north"
admin_username                 = "azureuser"
admin_password                 = "Obunh@12!"
mysql_admin_username           = "ally"
mysql_admin_password           = "Obunh@12!"
mysql_database_name            = "bookreviews_dev"
vnet_address_space             = ["10.0.0.0/16"]
public_subnet_address_prefixes = ["10.0.1.0/24"]
vm_size                        = "Standard_DS1_v2"
ssh_public_key                 = "~/.ssh/test_rsa.pub"
