trigger:
  paths:
    include:
      - terraform/**
  branches:
    include:
      - main

stages:
- stage: Terraform
  displayName: 'Provision Infrastructure'

  jobs:
  - job: Terraform_Apply
    displayName: 'Terraform Plan & Apply'
    pool:
      name: 'Ally CICD azure'

    steps:
    - script: |
        cd terraform

        echo "Terraform Init"
        terraform init -input=false

        echo "Terraform Plan"
        terraform plan -input=false -var-file="envs/dev.tfvars"

        echo "Terraform Apply"
        terraform apply -input=false -auto-approve -var-file="envs/dev.tfvars"
      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        AWS_DEFAULT_REGION: us-east-1
      displayName: 'Terraform Execution'