variable "region" {}
variable "admin_username" {}
variable "admin_password" {}
variable "subnet_id" {}
variable "security_group_id" {}
variable "application_name" {}
variable "environment" {}
variable "instance_type" {}
variable "ssh_key_name" {}
